# Generated by Django 4.2.7 on 2025-09-27 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='таърихи таваллуд')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='таърихи вафот')),
                ('biography', models.TextField(verbose_name='таржумаи ҳол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='poets/', verbose_name='акс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شاعر',
                'verbose_name_plural': 'شاعران',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='унвон')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='тавзеҳ')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='таърихи нашр')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='акси рӯи китоб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='poetry.poet', verbose_name='шоир')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتابها',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='унвон')),
                ('slug', models.SlugField(blank=True)),
                ('content', models.TextField(verbose_name='матн')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='тартиб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poetry.book', verbose_name='китоб')),
            ],
            options={
                'verbose_name': 'شعر',
                'verbose_name_plural': 'اشعار',
                'ordering': ['order', 'title'],
                'unique_together': {('book', 'slug')},
            },
        ),
    ]
