# Generated by Django 4.2.7 on 2025-09-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Китоб', 'verbose_name_plural': 'Китобҳо'},
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Шеър', 'verbose_name_plural': 'Шеърҳо'},
        ),
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ['name'], 'verbose_name': 'Шоир', 'verbose_name_plural': 'Шоирон'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Акси рӯи китоб'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Тавзеҳ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='poetry.poet', verbose_name='Шоир'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Санаи нашр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Унвон'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poetry.book', verbose_name='Китоб'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Тартиб'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Унвон'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='biography',
            field=models.TextField(verbose_name='Таржумаи ҳол'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Санаи таваллуд'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Санаи вафот'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ном'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='poets/', verbose_name='Акс'),
        ),
    ]
